### ISSUE TITLE
Global config with "docformatterrc"

### ISSUE THREAD

**Issue by humitos** [PyCQA/docformatter#10]
It would be great to have a `docformatterrc` like many other commands similar to this (flake8, autopep8, etc)

**Comment by aequitas** [comment]
Or include config in `setup.cfg` or similar like other tools.

**Comment by pwoolvett** [comment]
> Or include config in `setup.cfg` or similar like other tools.

`tox.ini`, `pyproject.toml`, ...

**Comment by aiguofer** [comment]
This would be great, especially for auto-applying docformatter on save when working on multiple projects with different configurations.

**Comment by ruohola** [comment]
IMO making support for just `pyproject.toml` would make the most sense. It really is the way to go in the future.
