### ISSUE TITLE
Combining ``--config`` and ``--in-place`` to resolve issues does not use configuration

### ISSUE THREAD

**Issue by fmigneault** [PyCQA/docformatter#112]
I run the following command and everything is reported as "OK" : 

```shell
docformatter \
	--pre-summary-newline \
	--wrap-descriptions 0 \
	--wrap-summaries 120 \
	--make-summary-multi-line \
	--in-place \
	--recursive \
	. 
```
Converting to the following: 
```shell
docformatter \
	--in-place \
	--recursive \
	--config setup.cfg \
	. 
```
And using `setup.cfg`: 
```cfg
[tool.docformatter]
recursive = true
wrap-descriptions = 0
wrap-summaries = 120
make-summary-multi-line = true
pre-summary-newline = true
```

I get many changes mostly ignoring `make-summary-multi-line`.
When I provide this parameter again in combination to `--config`, then fixes have the newlines again, but not the `wrap-summaries = 120` (use default instead). 

Running the same command with `--config` and replacing `--in-place` by `--check` reports everything is "OK" again, so this one considers the configuration file.

**Comment by fmigneault** [comment]
**Update**
Seems to be an issue with `[tool.docformatter]`. 
I replaced the section by `[docformatter]` and it works as expected.
The doc is misleading for `setup.cfg`.

**Comment by weibullguy** [comment]
This sounds like a documentation only issue.  There are two pieces of information missing or in error in the current documentation.

1. Command line arguments take precedence over configuration file values.
2. If using `setup.cfg`, the `[docformatter]` heading is the correct heading.
