### ISSUE TITLE
Message printed with `--help` change defaults on config detection

### ISSUE THREAD

**Issue by fmigneault** [PyCQA/docformatter#113]
I'm not sure if this is intentional or not, but I noticed this and wanted to make sure to report the potential issue.

When a configuration file (`setup.cfg`, `tox.ini` or `pyproject.toml`) is auto-detected in the local directory, values printed as defaults in `--help` change accordingly to parsed settings of this file. 
If the user runs the command from anywhere else than the directory where the config is located, those defaults suddenly change back. They also revert to the "real defaults" if we call ``docformatter --help --config ""``.

This could make users confused about "defaults" since those are usually reported as "value used if nothing was specified", but in this case they change based on a specified value.

**Comment by weibullguy** [comment]
Interesting.  But I know what's causing it and it's an easy fix.  Until then, the defaults are found in the [documentation](https://docformatter.readthedocs.io/en/latest/usage.html#use-from-the-command-line)
