### ISSUE TITLE
Allow configuring `exclude` via configuration file

### ISSUE THREAD

**Issue by tuukkamustonen** [PyCQA/docformatter#120]
The code seems to work so that defaults from a configuration file are loaded before initializing the argument parser, and then using the loaded values as defaults.

However, `exclude` variable is loaded among others, but it's not used as argument parsing default.

Add it the same way as other.

**Comment by keshavgaddhyan** [comment]
Hello, 

I am not able to use the exclude flag as an option from config file.

`[tool:docformatter]
recursive = true
wrap-summaries = 79
wrap-descriptions = 79
pre-summary-newline = true
make-summary-multi-line = true
exclude = [, "order/"]
`

I want to exclude the directory order inside my project diapason. 

The command I am running is `docformatter --config /home/kgaddhyan/PycharmProjects/diapason/setup.cfg diapason
`

Could you please help provide an example of how we can do this?

**Comment by weibullguy** [comment]
@keshavgaddhyan what version of docformatter are you using?

**Comment by keshavgaddhyan** [comment]
@weibullguy I am using 1.5.1. 

I am fine to exclude the files using the CLI command directly as well instead of reading from config file. However, it does not seem to be working. The python project name is `diapason` and `order` is a folder inside it. Could you perhaps give me an example of how can i do this?

**Comment by weibullguy** [comment]
@keshavgaddhyan using the configuration file for the exclude statement is not released yet.  If you want to use it, you'd need to install from the github repository:

`pip install git+https://github.com/PyCQA/docformatter.git@master`

From the CLI, this should do the trick:

`docformatter -r --exclude "order" diapason`
