### ISSUE TITLE
Allow in-place option in configuration files

### ISSUE THREAD

**Issue by janosh** [PyCQA/docformatter#122]
Setting

```cfg
# setup.cfg
[docformatter]
in-place = true
```

has no effect.

```sh
docformatter --config setup.cfg path/fo/file.py
```

still prints to terminal, leaving `path/fo/file.py` unchanged.

**Comment by weibullguy** [comment]
@janosh there are some options that can't be configured in the config files.  These are --in-place, --check, --diff, and --exclude.  These must be passed with the command.  This isn't documented as it should be, so it's understandable you reported this as a bug.  I am updating the title of this issue to reflect your report as a request for a new feature to be included in v1.6.0.
