### ISSUE TITLE
Allow showing the diff and exit 1 if files were changed

### ISSUE THREAD

**Issue by BenjaminSchubert** [PyCQA/docformatter#125]
## What is the current behavior?

Currently, you can either run:

- `docformatter file`, which will display the diff but always `exit 0` if nothing was changed
- `docformatter --check file`, which will only display the file name if there is a change and `exit 1`.

## What would you like?

I'd like to be able to both:

- show the diff
- exit 1if there is a change

in a single invocation, which would allow me to have an easier CI setup, while showing a nice diff to users.

I am happy to contribute the feature once/if there is an agreement that it is worth it and how we want to do it

**Comment by weibullguy** [comment]
> I am happy to contribute the feature once/if there is an agreement that it is worth it and how we want to do it
Please feel free to submit a pull request with your proposed solution.
