### ISSUE TITLE
Empty lines around class and method docstrings

### ISSUE THREAD

**Issue by mcflugen** [PyCQA/docformatter#130]
It would be nice if *docformatter* added/removed blank lines around the docstrings of classes and methods. According to the *pep257* and *numpy* conventions, there should be no blank lines either before or after method docstrings and classes should have a blank line after their docstring but not before.

This issue is pretty much the same as #51 but applied to classes and methods.

Thus, the following,
```python
class Foo:

    """Summary of Foo."""

    def foo(self):

        """Summary of foo."""

        pass
```
should be reformatted as,
```python
class Foo:
    """Summary of Foo."""

    def foo(self):
        """Summary of foo."""
        pass
```

**Comment by mcflugen** [comment]
FYI, modifying the *if* statement in *format.py* with the following seems to fix blank lines preceding method and class docstrings, 
```python
                if (
                    len(modified_tokens) <= 2
                    or token_type not in {tokenize.NL, tokenize.NEWLINE}
                    or modified_tokens[-1][0]
                    not in {tokenize.NL, tokenize.NEWLINE}
                    or modified_tokens[-2][1] != ":"
                    and modified_tokens[-2][0] != tokenize.COMMENT
                    or not modified_tokens[-2][4].lstrip().startswith(("def", "class"))
                ):
```

**Comment by stefsmeets** [comment]
What is the intended behaviour in the case below?

```
class Foo:

    def foo(self):
        pass
```

With the latest version of docformatter (1.5.1) this gets formatted as:

```
class Foo:
    def foo(self):
        pass
```

In my interpretation, it should be formatted as:

```
class Foo:

    def foo(self):
        pass
```

The result is that docformatter is now incompatible with the defaults for [yapf](https://github.com/google/yapf#knobs) (`blank_line_before_nested_class_or_def=True`). This causes issues in our autoformatting pipelines.

**Comment by bonastreyair** [comment]
what about this case? it removes all spaces and I think it shouldn't...

Given:
```python
class Foo:
    @abstractmethod
    def bar(self):
        """This is a description"""

    @abstractmethod
    def baz(self):
        """This is a second description"""

def new_function():
    """Description"""
    return "bar"
```

I get this:
```python
class Foo:
    @abstractmethod
    def bar(self):
        """This is a description."""
    @abstractmethod
    def baz(self):
        """This is a second description."""
def new_function():
    """Description."""
    return "bar"
```

When using it with `black`, it enforces to have an additional space between functions (as expected) and it returning to the first initial state... then failing all pre-commits
It did not happen in `1.5.1` but it does with latest `1.6.0` version that includes this PR.
