### ISSUE TITLE
URL matching only matches certain schemes, not others

### ISSUE THREAD

**Issue by thejcannon** [PyCQA/docformatter#146]
Specifically it split up an `s3` scheme URL :sob: 

Likely due to this: https://github.com/PyCQA/docformatter/blob/6706e9591c9f605956372eb1ee6228c465e0ac93/src/docformatter/syntax.py#L114

**Comment by TansyArron** [comment]
![Screenshot 2023-01-06 at 1 31 24 PM](https://user-images.githubusercontent.com/3494066/211076020-1a1637c1-75e4-4684-9980-746a6860f490.png)

**Comment by weibullguy** [comment]
@thejcannon I got ahead of myself releasing 1.5.0 to PyPi without sufficient testing.  Before I cause users anymore headaches, I'm providing release candidates for the brave to use and provide feedback.  If you'd like to use the next release candidate that should resolve your issue, you can install it with pip:

`pip install git+https://github.com/PyCQA/docformatter.git@v1.6.0.rc1`
