### ISSUE TITLE
v1.6.0-rc2 - Wrapping Differences from v1.5.1

### ISSUE THREAD

**Issue by rmartin16** [PyCQA/docformatter#160]
RC2 for v1.6.0 seems to be making different wrapping decisions than v1.5.1. The invocation of `docformatter` uses its default configuration. My best guess is the line length calculation is happening differently; in this example, if the preceding whitespace is included in the line length count, then the line will be considered to exceed the default allowed length.

```diff
     def install_metadata(self):
         """Metadata about the Visual Studio install.
 
-        Will be ``None`` if MSBuild the path to MSBuild has been provided
+        Will be ``None`` if MSBuild the path to MSBuild has been
+        provided
         explicitly, or is on the path.
 
-        Otherwise, a dictionary containing the install details from VSWhere.
+        Otherwise, a dictionary containing the install details from
+        VSWhere.
         """
         return self._install_metadata
```

**Comment by weibullguy** [comment]
@rmartin16 Can you give `v1.6.0-rc3` a try and see if its still causing you a problem?  It's not wrapping like above on my machine.

**Comment by weibullguy** [comment]
This is actually the same issue as reported in this comment <https://github.com/PyCQA/docformatter/issues/157#issuecomment-1427391967>.  Closing this to #157.
