### ISSUE TITLE
Support for Python 3.6 can be dropped

### ISSUE THREAD

**Issue by ollie-iterators** [PyCQA/docformatter#162]
As mentioned in Issue https://github.com/PyCQA/docformatter/issues/118, Python 3.6 support will be dropped 1 year post EOL. One year past Python 3.6's EOL was on December 23rd 2022, which has already happened.

That means that support for Python 3.6 can be removed.

**Comment by weibullguy** [comment]
Support was dropped in #149 and will be part of release 1.6.0.
