### ISSUE TITLE
Documentation refers to options that do not exist in the latest released version

### ISSUE THREAD

**Issue by tonnydourado** [PyCQA/docformatter#167]
In the [read-the-docs](https://docformatter.readthedocs.io/en/stable/requirements.html#current-implementation) documentation there's reference to a `--syntax` parameter, but passing this in the command line gives an error:

```console
(venv) ~$ docformatter --syntax sphinx bla.py
usage: docformatter [-h] [-i | -c] [-d] [-r] [-e [EXCLUDE [EXCLUDE ...]]] [--wrap-summaries length]
                    [--wrap-descriptions length] [--force-wrap] [--tab-width width] [--blank] [--pre-summary-newline]
                    [--pre-summary-space] [--make-summary-multi-line] [--close-quotes-on-newline] [--range line line]
                    [--docstring-length length length] [--non-strict] [--config CONFIG] [--version]
                    files [files ...]
docformatter: error: unrecognized arguments: --syntax
```

Am I missing something about how to use this parameter?

Python: tested on versions 3.8 (Ubuntu on WSL) and 3.9 (Windows)
docformatter: both `pip` and `pipx` report 1.5.1, but weirdly, `docformatter --version` reports 1.5.0 ?

**Comment by weibullguy** [comment]
Sorry, that section with the `--syntax` and `--black` shouldn't be in the latest docs.  Looks like I accidentally copied it over from my notes.  Both of those options are future (the `--black` option is being worked in #166).  The version info come from two different places for `pip` and `docformatter --version`.  The second didn't get updated, but that'll be fixed moving forward.
