### ISSUE TITLE
Bug (?): `pre-commit autoupdate` is backdating

### ISSUE THREAD

**Issue by jamesbraza** [PyCQA/docformatter#207]
My `pre-commit` config is `v1.6.5` (and [`v1.7.0` was just released](https://github.com/PyCQA/docformatter/releases/tag/v1.7.0)), and running `pre-commit autoupdate`:

```bash
> pre-commit autoupdate
[https://github.com/myint/docformatter] already up to date!
```

Then, manually changing it to `v1.7.0` and seeing what happens for `pre-commit autoupdate`:

```bash
> pre-commit autoupdate
[https://github.com/myint/docformatter] updating v1.7.0 -> v1.6.5
```

Why is `pre-commit` not accepting `v1.7.0`?

**Comment by weibullguy** [comment]
@jamesbraza should be working now.

**Comment by jamesbraza** [comment]
Nice it's working now.  What was the issue?  The recent commits on `master` branch seem unrelated

**Comment by weibullguy** [comment]
I boogered up the v1.7.0 tag somehow so it wasn't pointing to anything.  Deleted and re-tagged.  Badda bing, badda boom, it works!  Closing this issue since it's working for you now.
