### ISSUE TITLE
#noqa no longer works in 1.7.1

### ISSUE THREAD

**Issue by tuukkamustonen** [PyCQA/docformatter#226]
This used to work in 1.7.0 and earlier:

```py
class Foobar:
    # noqa
    """some gibb
    erish
    """
```

1.7.1 formats it despite `# noqa`.

By the way couldn't find any mention of `noqa` support in the docs? Should it be advertized?

**Comment by weibullguy** [comment]
`docformatter` has never recognized the # noqa decorator.  I ran your snippet through v1.7.1, v1.7.0, and v1.6.0 and, as it should, `docformatter` reformatted the docstring.  Please see #144 for a request to provide the ability to ignore part or all of a docstring.

**Comment by tuukkamustonen** [comment]
That's interesting, because the behavior differs in our codebase. Well, don't have time to dive deeper here, so will just stick with older version until #144 😎

Thanks for the project, appreciate your efforts!
