### ISSUE TITLE
Elaborate description with Sphinx cross-references is converted to field list.

### ISSUE THREAD

**Issue by electric-coder** [PyCQA/docformatter#227]
The following example is of a [PEP 257 multi-line docstring](https://peps.python.org/pep-0257/#multi-line-docstrings) with a summary line and an "elaborate description" paragraph that contains [Sphinx cross-references](https://www.sphinx-doc.org/en/master/usage/restructuredtext/roles.html#cross-referencing-syntax) in the "elaborate description".

The docstring does not contain any [docstring sections](https://www.sphinx-doc.org/en/master/usage/extensions/napoleon.html#docstring-sections) and (thus) no [reST field list](https://docutils.sourceforge.io/docs/ref/rst/restructuredtext.html#field-lists). This is because the class implements a series of abstract classes from [`collections.abc`](https://docs.python.org/3/library/collections.abc.html) and doesn't have any attributes of its own.

```py
class A:
    pass


class B:
    """Let's write a cross-reference to the above :class:`A`.

    Implements the following abstract class text text text text text text
    more text :class:`collections.abc.Set` text text text text text text
    :class:`frozenset` trailing text text text text text text text text
    :class:`collections.abc.Hashable` text text text text text text text text.
    """
```

When running docformatter 1.7.1 on the example it offers to:

1. Remove the text preceding the first cross-reference (possibly aiming to convert the `:class:` roles into a field list).
2. Introduce a space between the role and the opening backtick, turning ```:class:`title <link>` ``` into ```:class: `title <link>` ```. (This change would break the cross-references).

```none
@@ -9,10 +9,10 @@
 class B:
     """Let's write a cross-reference to the above :class:`A`.
 
-    Implements the following abstract class text text text text text text
-    more text :class:`collections.abc.Set` text text text text text text
-    :class:`frozenset` trailing text text text text text text text text
-    :class:`collections.abc.Hashable` text text text text text text text text.
+    Implements the following abstract class text text text text text text more text
+    :class: `collections.abc.Set` text text text text text text
+    :class: `frozenset` trailing text text text text text text text text
+    :class: `collections.abc.Hashable` text text text text text text text text.
     """
```

Notice that if the docstring did have a docstring section docformatter would format it correctly, the following example works as expected:

```py
class A:
    pass


class B:
    """Let's write a cross-reference to the above :class:`A`.

    Implements the following abstract class text text text text text text
    more text :class:`collections.abc.Set` text text text text text text
    :class:`frozenset` trailing text text text text text text text text
    :class:`collections.abc.Hashable` text text text text text text text text.

    Args:
        an_arg (str): Explains the arg.
    """
```

Using docformatter 1.7.1 with the following settings in `pyproject.toml`:

```toml
[tool.docformatter]
black = true
wrap-descriptions = 88
wrap-summaries = 88
```

A screenshot to help visualize the desired result:

![docformatter1](https://github.com/PyCQA/docformatter/assets/60424310/9347e03b-d801-4107-9ace-2a75644e7548)

**Comment by weibullguy** [comment]
v1.7.2-rc4 fixes this.

**Comment by weibullguy** [comment]
Closing this issue to #231.
