### ISSUE TITLE
release/v1.7.4 [Community Feedback]

### ISSUE THREAD

**Issue by weibullguy** [PyCQA/docformatter#250]
Tracker for issues related to release v1.7.4 (see https://github.com/PyCQA/docformatter/pull/249). Please report all issues encountered while using the v1.7.4 release candidates here.

To install a release candidate:

pip install git+https://github.com/pycqa/docformatter@v1.7.4-rc1

where the rc1 would be replaced by the release candidate you'd like to use.

Fixes #243
Fixes #245

**Comment by AntoineD** [comment]
1.7.4-rc1 fails on this example:

def f():
    """CC.

    C.

    C c :math:`[0, 1]`.
    """ 
it produces

def f():
    """CC.

    C.

    C c

    :math:`[0, 1]`.
    """
