### ISSUE TITLE
Bug: not splitting two sentence summary into description

### ISSUE THREAD

**Issue by jamesbraza** [PyCQA/docformatter#275]
Please see the below Python snippet, I am using Python 3.11 with `docformatter==1.7.5`:

```python
# a.py

def foo() -> None:
    """I am a first sentence this long. I am another sentence that I would like to be in summary."""
```

Running `docformatter --black --close-quotes-on-newline a.py` formats it to:

```python
# a.py

def foo() -> None:
    """
    I am a first sentence this long.

    I am another sentence that I would like to be in summary.
    """
```

I understand why the summary line is being split, because it violates the 88-char summary wrap length.  However, I would like `docformatter` to avoid splitting the summary into a description like so:

```python
# a.py

def foo() -> None:
    """
    I am a first sentence this long. I am another sentence that I would like to be in
    summary.
    """
```

I think what this warrants is:
- New arg `--no-split-summary-description` or `--no-split-first-sentence`
- Or a new regex to split the first sentence with, which can be set to `\n`

**Comment by weibullguy** [comment]
Per PEP-257:

> Multi-line docstrings consist of a summary line just like a one-line docstring, followed by a blank line, followed by a more elaborate description.

And and one-line docstring, per PEP-257:

> The docstring is a phrase ending in a period. It prescribes the function or method’s effect as a command (“Do this”, “Return that”), not as a description; e.g. don’t write “Returns the pathname …”.

The example you provide is a multi-line docstring per PEP-257 and is being handled appropriately.
