### ISSUE TITLE
Unexpected key(s) present on https://github.com/myint/docformatter: language

### ISSUE THREAD

**Issue by hughplay** [PyCQA/docformatter#297]
Running `pre-commit -a` failed:

```
[WARNING] Unexpected key(s) present on https://github.com/myint/docformatter: language
An error has occurred: InvalidManifestError: 
==> File /home/xxx/.cache/pre-commit/repoy0mt_548/.pre-commit-hooks.yaml
==> At Hook(id='docformatter-venv')
==> At key: language
=====> Expected one of conda, coursier, dart, docker, docker_image, dotnet, fail, golang, haskell, lua, node, perl, pygrep, python, r, ruby, rust, script, swift, system but got: 'python_venv'
Check the log at /home/xxx/.cache/pre-commit/pre-commit.log
```

After searching, I found:

- https://stackoverflow.com/a/79057818
- https://github.com/pre-commit/pre-commit/releases/tag/v4.0.0

> it looks like you've recently updated to pre-commit 4.0.0 which removes support for language: python_venv. this has been warning for quite a while now but fortunately language: python_venv is just an alias to language: python
>
>if you've set language: python_venv in your configuration (.pre-commit-config.yaml) directly, you can run pre-commit migrate-config to automatically update that to language: python
>
>if it's in an external repository (which is what it looks like given your error message above) you'll want to run pre-commit autoupdate which ~usually will bump you to a version that is fixed -- however if that does not fix your problem you'll need to report the issue to whatever repo is setting language: python_venv in their .pre-commit-hooks.yaml (in this example here it looks like the repository is https://example.com/some/repo and the hook id is some-hook-id)

**Comment by finswimmer** [comment]
Duplicate of #289

**Comment by hughplay** [comment]
Got it. Thank you.
