### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by wchargin** [PyCQA/docformatter#42]
I’m adding *Black* to a large-ish project that previously had no Python
autoformatting. I found this project from the Black docstrings thread:
<https://github.com/psf/black/issues/144#issuecomment-394064995>

I installed it and ran `docformatter -i -r .`, and it worked perfectly,
and the output still passes `black --check`. You’ve saved me quite a bit
of time determining how to effect this 7K-line diff myself. Thank you!

**Comment by weibullguy** [comment]
You're welcome!
