### ISSUE TITLE
I have problem

### ISSUE THREAD

**Issue by tw1sterPL** [PyCQA/docformatter#48]
Hello,

When I want to use  I get an error:
The Python path set in the "python.pythonPath" setting is invalid or points to Python 2. Check the value or clear the setting to use the global Python installation. The extension is not compatible with Python 2.

settings.json: 
"python.jediEnabled": false,
"[python]": {
    "editor.defaultFormatter": "iansan5653.format-python-docstrings"
  }
System: Ubuntu 19.10

**Comment by weibullguy** [comment]
@tw1sterPL This doesn't look like a docformatter problem.  Can you provide more information regarding your issue and how it's related to docformatter?  Otherwise, I'm going to close this issue as invalid.  Thanks.
