### ISSUE TITLE
Automatic wrapping and force wrapping issues

### ISSUE THREAD

**Issue by thebuzzstop** [PyCQA/docformatter#68]
Long descriptions are not being wrapped as expected.

When I use the --force-wrap option the entire docstring is properly wrapped but a Sphinx **_param_** is also wrapped which is undesirable.

Usage:

- docformatter v1.4 inside PyCharm
- invoked as an external tool with the following command line
- docformatter --force-wrap --wrap-descriptions 72 --wrap-summaries 79 --in-place --range 1014 1019 myfile.py

Here's a screenshot of the before:
![image](https://user-images.githubusercontent.com/10444222/104784415-356be700-5756-11eb-8268-33d8f7fe5520.png)

Here's a screenshot after running docformatter:
![image](https://user-images.githubusercontent.com/10444222/104784481-61876800-5756-11eb-8eda-5bdf8db4fb21.png)
Note that the description was not line-wrapped.

Here's a screenshot after running docformatter with the --force-wrap option:
![image](https://user-images.githubusercontent.com/10444222/104784592-a01d2280-5756-11eb-9fe6-e6ad0c65c571.png)
Note that the description was line-wrapped but the Sphinx **_param_** was also wrapped.

**Comment by weibullguy** [comment]
docformatter's goal is to reformat docstrings in accordance with PEP-257.  Sphinx directives are not really addressed by PEP-257.  That said, Sphinx directives are ubiquitous in docstrings and docformatter should handle them properly.  See also #78
