### ISSUE TITLE
Start sentence with capital letter

### ISSUE THREAD

**Issue by Borda** [PyCQA/docformatter#76]
Hi, I have noticed that the docstring puts "." at the summary end but does not make the first letter capital...
I think that it could be quite simple to edit this, what do you think?
For example this original:
```
"""set minimal torch version"""
```
is converted to:
```
"""set minimal torch version."""
```

**Comment by weibullguy** [comment]
PEP-257 isn't explicit regarding capitalizing the first word in the summary, but it implies such behavior in it's examples.  Additionally, pydocstyle will raise a warning (D403) if the first word isn't capitalized.
