### ISSUE TITLE
Alternative to docformatter?

### ISSUE THREAD

**Issue by mdczaplicki** [PyCQA/docformatter#85]
Seems that this project is abandoned. Do you know any alternatives?

**Comment by DanielNoord** [comment]
Shameless plug but I and other maintainers of `pylint` have been working on https://github.com/DanielNoord/pydocstringformatter.
It does not have all functionality yet, but we are getting close and have squashed some of the main bugs we found in `docstringformatter`. 

We are also happy to work on anything that is currently missing!
