### ISSUE TITLE
Definitions get corrupted when signature has pending comment-directive

### ISSUE THREAD

**Issue by krzysztof3-wisniewski** [PyCQA/docformatter#97]
Follwing code should be simply ignored, as it doesn't contain any docstring:
```python
def pytest_addoption(parser: pytest.Parser) -> None:  # pragma: no cover
    register_toggle.pytest_addoption(parser)
```
But that's not the case, it is reformatted as
```python
def pytest_addoption(parser: pytest.Parser) -> None:  # pragma: no cover  register_toggle.pytest_addoption(parser)

```
Which of course causes syntax error.
Problem was spotted on ae24186a06e8cae89d4bf0a9a9a66e4ced053beb, and it seems **not** to appear on c6d643b531d9cedebe1be3aa16b0f607d450fe9f.

**Comment by weibullguy** [comment]
@krzysztof3-wisniewski Can you check if PR #99 fixes this for you.  I think I have the conditional figured out to handle comments in-line with the function definition.  TIA

**Comment by krzysztof3-wisniewski** [comment]
Yes, #99 seems to solve both #97 and #98

**Comment by weibullguy** [comment]
I just started helping out a couple weeks ago and I've been focusing on getting the open issues and PRs that've been around for several years closed and merged.  I'm on vacation next week; I'll try to get a new release on PyPi before I leave, but I also don't want to rush it and leave a broken package out there.  If I don't get to it before I leave, I'll get one out as soon as I get back.
